### ISSUE TITLE
Drop rustc-serialize support

### ISSUE THREAD

**Issue by dtolnay** [alkis/decimal#26]
According to [Rust release milestone predictions](https://internals.rust-lang.org/t/rust-release-milestone-predictions/4591?u=dtolnay), rustc-serialize is scheduled to be deprecated in next month's beta release of Rust.

**Comment by alkis** [comment]
Thanks for the heads up. I think even after deprecation it is good to support it, since several codebases might be using it even post deprecation. Once it is removed from rust we should remove it from d128 as well.

**Comment by dtolnay** [comment]
Makes sense. I guess the opposite argument would be that codebases that are using an outdated serialization library will always be able to use an outdated `decimal` as well. They can just stick to the latest version that provides rustc-serialize support. In the meantime, new users will not need to wade past irrelevant code and irrelevant cargo cfgs when reviewing the code or documentation of this crate.

**Comment by alkis** [comment]
I would agree if the support was opt-out. But since `rustc-serialize` is opt-in I think it is fine to stay in until removed from rust itself. The code is minimal to support it so it barely costs anything in maintenance.
