### ISSUE TITLE
Update serde to 1.0.0

### ISSUE THREAD

**Issue by kosta** [alkis/decimal#30]
Would you be willing to merge a PR that uses serde 1.0.0?

**Comment by alkis** [comment]
Yes. That would be great!

**Comment by kkartaltepe** [comment]
Can you please push this out to crates.io? Perhaps as a 1.0.1 version or something.

**Comment by alkis** [comment]
Done.

**Comment by kosta** [comment]
Sorry for commenting so late, but: This should actually be 2.0.0 not 1.0.1 because updating from serde 0.8 to 1.0 is a breaking change and thus requires a new major version.

If you want to strictly follow semver, you could yank the 1.0.1 from crates.io and publish it as 2.0.0 instead.

If no one complains, I'm not sure whether this is worth the effort.
