### ISSUE TITLE
big-endian support

### ISSUE THREAD

**Issue by alkis** [alkis/decimal#4]
Currently libdecNumber.a is compiled with little-endian support. build.rs needs to detect big or little endian target architecture and pass DECLITEND=0 (for little) or DECLITEND=1 (for big).

**Comment by trolleyman** [comment]
Is this what you were thinking?

```rust
// build.rs
extern crate gcc;

fn main() {
    let endianness = if cfg!(endian = "little") {
        "0"
    } else {
        "1"
    };
    gcc::Config::new()
        .include("decNumber")
        .file("decNumber/decContext.c")
        .file("decNumber/decDouble.c")
        .file("decNumber/decNumber.c")
        .file("decNumber/decPacked.c")
        .file("decNumber/decQuad.c")
        .file("decNumber/decSingle.c")
        .file("decNumber/decimal128.c")
        .file("decNumber/decimal32.c")
        .file("decNumber/decimal64.c")
        .define("DECNUMDIGITS", Some("34"))
        .define("DECLITEND", Some(endianness))
        .compile("libdecNumber.a");
}

**Comment by alkis** [comment]
Is the endian feature something rust exports by default?

**Comment by trolleyman** [comment]
Yeah, it's [here](https://doc.rust-lang.org/nightly/reference.html#conditional-compilation) in the reference and [here](http://doc.rust-lang.org/std/macro.cfg!.html) in the docs.

**Comment by alkis** [comment]
Oh awesome! Thanks for the pointer :-)
