### ISSUE TITLE
status of the project

### ISSUE THREAD

**Issue by matu3ba** [alkis/decimal#63]
One maintainer of ion here. We have [this issue](https://gitlab.redox-os.org/redox-os/ion/-/issues/996#note_22775), which is probably due to not merging the branch [uninit-fix](https://github.com/alkis/decimal/tree/uninit-fix).
What is missing to get this merged?

Do you plan to get active again in the near future or would you be okay with a fork?

**Comment by matu3ba** [comment]
wrong project-.-

**Comment by probablykasper** [comment]
Check https://github.com/alkis/decimal/issues/59#issuecomment-787016719

**Comment by jonathanstrong** [comment]
@matu3ba [version 2.1.0](https://crates.io/crates/decimal/2.1.0) has just been published, which merges the unint-fix branch.
