### ISSUE TITLE
d128 constants

### ISSUE THREAD

**Issue by trolleyman** [alkis/decimal#7]
Currently there is no way to have `d128` constants in this library. I have worked around the problem by directly hard-coding values in and making the internal structure of `d128` public. My current `consts.rs` looks like this:

``` rust
pub const D0: d128 = d128{ bytes: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 34] };
pub const D1: d128 = d128{ bytes: [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 34] };
pub const D2: d128 = d128{ bytes: [2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 34] };

pub const DP5: d128 = d128{ bytes: [5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 192, 7, 34] };

pub const D90: d128 = d128{ bytes: [26, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 34] };
pub const D180: d128 = d128{ bytes: [138, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 34] };
pub const D200: d128 = d128{ bytes: [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 34] };

/// e
pub const DE: d128 = d128{ bytes: [98, 75, 23, 231, 90, 224, 213, 84, 68, 150, 46, 45, 132, 249, 255, 41] };
/// π
pub const DPI: d128 = d128{ bytes: [131, 230, 181, 218, 208, 98, 226, 180, 251, 179, 83, 235, 26, 204, 255, 45] };
/// π/2
pub const DPI2: d128 = d128{ bytes: [209, 231, 188, 113, 104, 49, 101, 236, 177, 246, 166, 233, 15, 239, 255, 37] };
/// φ
pub const DGOLDEN_RATIO: d128 = d128{ bytes: [56, 151, 199, 163, 186, 4, 185, 232, 97, 242, 238, 204, 128, 241, 255, 37] };
/// ∞
pub const DINFINITY: d128 = d128{ bytes: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 120] };
/// -∞
pub const DNEG_INFINITY: d128 = d128{ bytes: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 248] };
```

However, I propose adding a d128::from_bytes function. It would take the raw bytes in as little endian, and convert to the system endianness.

``` rust
impl d128 {
    #[cfg(target_endian = "little")]
    pub const fn from_bytes(b: [u8; 16]) -> d128 {
        d128{ bytes: b }
    }
    #[cfg(target_endian = "big")]
    pub const fn from_bytes(b: [u8; 16]) -> d128 {
        d128{ bytes: [b[15], b[14], b[13], b[12], b[11], b[10], b[9], b[8], b[7], b[6], b[5], b[4], b[3], b[2], b[1], b[0]] }
    }
}
```

Thoughts?

**Comment by alkis** [comment]
Will something like this work?

```rust
const D0 = d128!(0);
const D1 = d128!(1);
// more consts here

impl d128 {
  pub fn zero() -> d128 { D0 }
  pub fn one() -> d128 { D1 }
  // more functions here
}

Also are we sure we want more than 0, 1, +inf, -inf and nan?

**Comment by trolleyman** [comment]
`const D0 = d128!(0);` doesn't work atm as `d128!(0)` just becomes `{ use std::str::FromStr; d128::from_str(0) }` which isn't a constant function. Another option is reimplementing the `d128` macro as a plugin that converts the string at compile time.

**Comment by trolleyman** [comment]
At the moment I think `d128::from_bytes` is a good workaround for the moment.

**Comment by alkis** [comment]
How about:

```rust
impl d128 {
  pub fn zero() -> d128 { d128!(0) }
  pub fn one() -> d128 { d128!(1) }
  // more functions here
}
```

This means we will have the functions but they will be inefficient. When plugins are ready we can make them fast.

My main problem with with_bytes it is that it is very hard to use.

**Comment by trolleyman** [comment]
Yeah, the problem with this is that it is still calculating the numbers at runtime. Is there a way, using the plugin API, to compile the library and use one of the functions, then get the return value and hard code it in?

**Comment by alkis** [comment]
I don't know if there is a way. But what I know is that it is still not stabilized and available only on nightly. For that reason I want to wait until it makes it to beta before implementing something for it.
